<?xml version="1.0"?>
<testsuites>
<testsuite name="Root Suite" timestamp="2021-03-31T13:28:24" tests="0" file="cypress\integration\FirstTest.spec.js" time="0.0000" failures="0"></testsuite>
<testsuite name="Test with Backend" timestamp="2021-03-31T13:28:24" tests="5" time="18.4180" failures="0">
  
  <testcase name="Test with Backend verify correct request and responce" time="6.2570" classname="verify correct request and responce"></testcase>
  
  <testcase name="Test with Backend should gave tags with routing object" time="1.5340" classname="should gave tags with routing object"></testcase>
  
  <testcase name="Test with Backend verify global feed likes count" time="2.2020" classname="verify global feed likes count"></testcase>
  
  <testcase name="Test with Backend intercepting and modifying the request and responce" time="3.5290" classname="intercepting and modifying the request and responce"></testcase>
  
  <testcase name="Test with Backend delete a new article in the global feed" time="4.8960" classname="delete a new article in the global feed"></testcase>
  
</testsuite>

<testsuite name="Root Suite" timestamp="2021-03-31T13:29:03" tests="0" file="cypress\integration\SecondTest.spec.js" time="0.0000" failures="0"></testsuite>
<testsuite name="Test log out" timestamp="2021-03-31T13:29:04" tests="1" time="0.0000" failures="1">
  
  <testcase name="Test log out verify use can log out successfully" time="0.0000" classname="verify use can log out successfully">
    
    <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\SecondTest.spec.js:37733:27)]]></failure>
    
  </testcase>
  
</testsuite>

</testsuites>